<?php

namespace AppBundle\Repository;

/**
 * BcbpEventDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcbpEventDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
