<?php

namespace AppBundle\Repository;

/**
 * BcbpMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcbpMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
