<?php

namespace AppBundle\Repository;

/**
 * BcbpEventHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcbpEventHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
