<?php

namespace AppBundle\Repository;

/**
 * BcbpEventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcbpEventTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
