<?php

namespace AppBundle\Repository;

/**
 * BcbpPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BcbpPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
