<?php

namespace AppBundle\Repository;

/**
 * KamadaHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamadaHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
