<?php

namespace AppBundle\Repository;

/**
 * KamadaDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamadaDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
