<?php

namespace AppBundle\Repository;

/**
 * KforceDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KforceDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
