<?php

namespace AppBundle\Repository;

/**
 * KforceHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KforceHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
