<?php

namespace AppBundle\Repository;

/**
 * PrelistingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrelistingDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
