<?php

namespace AppBundle\Repository;

/**
 * PrelistingHeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrelistingHeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
